# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zekemedley/Desktop/corelight/paraglob/Paraglob-2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zekemedley/Desktop/corelight/paraglob/Paraglob-2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zekemedley/Desktop/corelight/paraglob/Paraglob-2/CMakeFiles /home/zekemedley/Desktop/corelight/paraglob/Paraglob-2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zekemedley/Desktop/corelight/paraglob/Paraglob-2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named paraglob.out

# Build rule for target.
paraglob.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 paraglob.out
.PHONY : paraglob.out

# fast build rule for target.
paraglob.out/fast:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/build
.PHONY : paraglob.out/fast

#=============================================================================
# Target rules for targets named ahocorasick

# Build rule for target.
ahocorasick: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ahocorasick
.PHONY : ahocorasick

# fast build rule for target.
ahocorasick/fast:
	$(MAKE) -f ahocorasick/CMakeFiles/ahocorasick.dir/build.make ahocorasick/CMakeFiles/ahocorasick.dir/build
.PHONY : ahocorasick/fast

AhoCorasickPlus.o: AhoCorasickPlus.cpp.o

.PHONY : AhoCorasickPlus.o

# target to build an object file
AhoCorasickPlus.cpp.o:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/AhoCorasickPlus.cpp.o
.PHONY : AhoCorasickPlus.cpp.o

AhoCorasickPlus.i: AhoCorasickPlus.cpp.i

.PHONY : AhoCorasickPlus.i

# target to preprocess a source file
AhoCorasickPlus.cpp.i:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/AhoCorasickPlus.cpp.i
.PHONY : AhoCorasickPlus.cpp.i

AhoCorasickPlus.s: AhoCorasickPlus.cpp.s

.PHONY : AhoCorasickPlus.s

# target to generate assembly for a file
AhoCorasickPlus.cpp.s:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/AhoCorasickPlus.cpp.s
.PHONY : AhoCorasickPlus.cpp.s

benchmark.o: benchmark.cpp.o

.PHONY : benchmark.o

# target to build an object file
benchmark.cpp.o:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/benchmark.cpp.o
.PHONY : benchmark.cpp.o

benchmark.i: benchmark.cpp.i

.PHONY : benchmark.i

# target to preprocess a source file
benchmark.cpp.i:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/benchmark.cpp.i
.PHONY : benchmark.cpp.i

benchmark.s: benchmark.cpp.s

.PHONY : benchmark.s

# target to generate assembly for a file
benchmark.cpp.s:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/benchmark.cpp.s
.PHONY : benchmark.cpp.s

driver.o: driver.cpp.o

.PHONY : driver.o

# target to build an object file
driver.cpp.o:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/driver.cpp.o
.PHONY : driver.cpp.o

driver.i: driver.cpp.i

.PHONY : driver.i

# target to preprocess a source file
driver.cpp.i:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/driver.cpp.i
.PHONY : driver.cpp.i

driver.s: driver.cpp.s

.PHONY : driver.s

# target to generate assembly for a file
driver.cpp.s:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/driver.cpp.s
.PHONY : driver.cpp.s

paraglob.o: paraglob.cpp.o

.PHONY : paraglob.o

# target to build an object file
paraglob.cpp.o:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/paraglob.cpp.o
.PHONY : paraglob.cpp.o

paraglob.i: paraglob.cpp.i

.PHONY : paraglob.i

# target to preprocess a source file
paraglob.cpp.i:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/paraglob.cpp.i
.PHONY : paraglob.cpp.i

paraglob.s: paraglob.cpp.s

.PHONY : paraglob.s

# target to generate assembly for a file
paraglob.cpp.s:
	$(MAKE) -f CMakeFiles/paraglob.out.dir/build.make CMakeFiles/paraglob.out.dir/paraglob.cpp.s
.PHONY : paraglob.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... paraglob.out"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... ahocorasick"
	@echo "... AhoCorasickPlus.o"
	@echo "... AhoCorasickPlus.i"
	@echo "... AhoCorasickPlus.s"
	@echo "... benchmark.o"
	@echo "... benchmark.i"
	@echo "... benchmark.s"
	@echo "... driver.o"
	@echo "... driver.i"
	@echo "... driver.s"
	@echo "... paraglob.o"
	@echo "... paraglob.i"
	@echo "... paraglob.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

